version: '3.9'
services:
  # back-end api built with golang
  golang:
    build: 
      context: golang
      target: dev
    volumes:
      - ./golang:/root
    ports:
      - 5000:5000
    env_file: .env
    depends_on:
      - postgres

  # front-end built with react
  react:
    build: 
      context: react
      target: dev
    volumes:
      - ./react:/root
    ports:
      - 3000:3000
      
  # caddy is used for ssl termination
  caddy:
    image: caddy:latest
    restart: unless-stopped
    volumes:
      - $PWD/caddy/conf/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/caddy/www:/srv
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - 80:80
      - 443:443
    depends_on:
      - react
      - golang

  # postgres is our primary data store
  postgres:
    build: postgres
    volumes:
      - ./postgres/migrations:/docker-entrypoint-initdb.d/migrations

volumes:
  caddy_data:
  caddy_config:
