version: '3.9'
services:
  # back-end api built with golang
  golang-prod:
    restart: always
    build: 
      context: golang
      target: prod
    ports:
      - "5000:5000"
    env_file: .env

  # front-end built with react
  react-prod:
    restart: always
    build: 
      context: react
      target: prod
    ports:
      - "3000:3000"
  # caddy is used for ssl termination
  caddy-prod:
    image: caddy:latest
    restart: unless-stopped
    volumes:
      - $PWD/caddy/conf/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/caddy/www:/srv
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - 80:80
      - 443:443
    depends_on:
      - golang-prod
      - react-prod

volumes:
  caddy_data:
  caddy_config:
