version: '3.9'
services:
  # back-end api built with golang
  golang:
    build: 
      context: golang
      target: dev
    volumes:
      - ./golang:/root
    ports:
      - "5000:5000"
    env_file: .env.example
    depends_on:
      - postgres

  # front-end built with react
  react:
    build: 
      context: react
      target: dev
    volumes:
      - ./react:/root
    ports:
      - "3000:3000"
      
  # caddy is used for ssl termination
  caddy:
    image: abiosoft/caddy:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - agree
      - email xxuechin@gmail.com
    volumes:
      - "./caddy/conf/Caddyfile:/etc/Caddyfile"
      - "./caddy/.caddy:/root/.caddy"
      - "./caddy/logs:/opt/logs"
      - "./caddy/www:/opt/www"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - react
      - golang

  # postgres is our primary data store
  postgres:
    build: postgres
    volumes:
      - ./postgres/migrations:/docker-entrypoint-initdb.d/migrations



