version: '3.9'
services:
  # back-end api built with golang
  golang:
    build: 
      context: golang
      target: dev
    volumes:
      - ./golang:/root
    ports:
      - "5000:5000"
    env_file: .env.example
    depends_on:
      - postgres

  # front-end built with react
  react:
    build: 
      context: react
      target: dev
    volumes:
      - ./react:/root
    ports:
      - "3000:3000"

  # nginx is used for ssl termination
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./public:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - react
      - golang

  # build for certbot
  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/certbot --email xxuechin@gmail.com --agree-tos --no-eff-email -d selcode.cn -d www.selcode.cn
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - ./certbot/data:/var/www/certbot

  # postgres is our primary data store
  postgres:
    build: postgres
    volumes:
      - ./postgres/migrations:/docker-entrypoint-initdb.d/migrations



